### ISSUE TITLE
rego_type_error: undefined function json.patch

### ISSUE THREAD

**Issue by ghost** [fugue/example-tf-circleci-part-2#1]
Followed the example but got this error message, seems a new function got introduced but isn't supported by conftest?

Checking project
terraform init -input=false -backend=false
terraform plan -input=false -refresh=false -out=plan.tfplan
Checking project/remote_state
terraform init -input=false -backend=false
terraform plan -input=false -refresh=false -out=plan.tfplan
Checking project/staging
terraform init -input=false -backend=false
terraform plan -input=false -refresh=false -out=plan.tfplan
Error: build compiler: compiling: 3 errors occurred:
policy/regula/lib/fugue_resource_view.rego:33: rego_type_error: undefined function json.patch
policy/regula/lib/fugue_resource_view.rego:110: rego_type_error: undefined function json.patch
policy/regula/lib/fugue_resource_view.rego:259: rego_type_error: undefined function json.patch
Usage:
  conftest test <file> [file...] [flags]

Running the latest versions of OPA and Conftest
_conftest -v_
Version: 0.22.0
Commit: 07a60e7
Date: 2020-11-14T09:21:01Z

_opa version_
Version: 0.25.2
Build Commit: 4c6e524
Build Timestamp: 2020-12-08T16:56:43Z
Build Hostname: 3bb58334a5a9
Go Version: go1.14.9
WebAssembly: unavailable

**Comment by ghost** [comment]
Cloned the Conftest repo, bumped the version for OPA to 0.25.2 (in the go.mod file) and ran the _go build_  command and uploaded it to my own repo. With this OPA version bump it works.

**Comment by jaspervdj-luminal** [comment]
@marc181982 Yep, that sounds good!  It sounds like the issue was that `conftest` was using an older OPA.  Hopefully they do a release soon so you don't have to build it from source.  I'm closing this issue for now but feel free to reopen if things are still wonky.
